import type { DishType, HkDistrict, HkRegion } from "@/common/constants/hongKong";

export type SeedDish = {
	name: string;
	price: number;
	photoUrl: string;
};

export type SeedRestaurant = {
	name: string;
	region: HkRegion;
	district: HkDistrict;
	dishType: DishType;
	rating: number;
	reviewCount: number;
	dishes: SeedDish[];
};

const unsplash = (id: string) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=70`;

// Verified Unsplash photo pools, grouped by cuisine/dish family.
const PHOTO = {
	cantonese: [unsplash("1519708227418-c8fd9a32b7a2"), unsplash("1414235077428-338989a2e8c0")],
	dimSum: [
		unsplash("1496116218417-1a781b1c416c"),
		unsplash("1563245372-f21724e3856d"),
		unsplash("1541696490-8744a5dc0228"),
	],
	chaChaanTeng: [unsplash("1495474472287-4d71bcdd2085"), unsplash("1509042239860-f550ce710b93")],
	cafe: [
		unsplash("1559847844-5315695dadae"),
		unsplash("1512621776951-a57141f2eefd"),
		unsplash("1546069901-ba9599a7e63c"),
	],
	dessert: [
		unsplash("1551024506-0bccd828d307"),
		unsplash("1563805042-7684c019e1cb"),
		unsplash("1488477181946-6428a0291777"),
		unsplash("1470124182917-cc6e71b22ecc"),
	],
	noodles: [unsplash("1585032226651-759b368d7246"), unsplash("1552611052-33e04de081de")],
	ramen: [unsplash("1569718212165-3a8278d5f624"), unsplash("1591814468924-caf88d1232e1")],
	sushi: [unsplash("1579871494447-9811cf80d66c"), unsplash("1553621042-f6e147245754")],
	seafood: [
		unsplash("1532347922424-c652d9b7208e"),
		unsplash("1559737558-2f5a35f4523b"),
		unsplash("1615141982883-c7ad0e69fd62"),
	],
	hotPot: [
		unsplash("1529042410759-befb1204b468"),
		unsplash("1583032015879-e5022cb87c3b"),
		unsplash("1562565652-a0d8f0c59eb4"),
	],
	thai: [unsplash("1617093727343-374698b1b08d"), unsplash("1559314809-0d155014e29e")],
	vietnamese: [unsplash("1553163147-622ab57be1c7"), unsplash("1582878826629-29b7ad1cdc43")],
	korean: [
		unsplash("1562967914-608f82629710"),
		unsplash("1626082927389-6cd097cdc6ec"),
		unsplash("1590301157890-4810ed352733"),
		unsplash("1498654896293-37aacf113fd9"),
	],
	indian: [
		unsplash("1603133872878-684f208fb84b"),
		unsplash("1585937421612-70a008356fbe"),
		unsplash("1631452180519-c014fe946bc7"),
	],
	italian: [
		unsplash("1565299624946-b28f40a0ae38"),
		unsplash("1473093295043-cdd812d0e601"),
		unsplash("1621996346565-e3dbc646d9a9"),
		unsplash("1551183053-bf91a1d81141"),
	],
	western: [unsplash("1504674900247-0877df9cc836"), unsplash("1551782450-a2132b4ba21d")],
	french: [unsplash("1504674900247-0877df9cc836"), unsplash("1512621776951-a57141f2eefd")],
	street: [
		unsplash("1476224203421-9ac39bcb3327"),
		unsplash("1567620905732-2d1ec7ab7445"),
		unsplash("1565958011703-44f9829ba187"),
	],
	bakery: [unsplash("1565958011703-44f9829ba187"), unsplash("1567620905732-2d1ec7ab7445")],
	shanghainese: [
		unsplash("1563245372-f21724e3856d"),
		unsplash("1541696490-8744a5dc0228"),
		unsplash("1519708227418-c8fd9a32b7a2"),
	],
	sichuan: [unsplash("1529042410759-befb1204b468"), unsplash("1519708227418-c8fd9a32b7a2")],
	taiwanese: [unsplash("1563245372-f21724e3856d"), unsplash("1585032226651-759b368d7246")],
	japanese: [
		unsplash("1591814468924-caf88d1232e1"),
		unsplash("1553621042-f6e147245754"),
		unsplash("1512621776951-a57141f2eefd"),
	],
} as const;

export const hkRestaurants: SeedRestaurant[] = [
	// ---------------------------------------------------------------------------
	// Hong Kong Island
	// ---------------------------------------------------------------------------
	// Central & Western
	{
		name: "Yung Kee",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Cantonese",
		rating: 4.2,
		reviewCount: 3120,
		dishes: [
			{ name: "Roast Goose (Half)", price: 320, photoUrl: PHOTO.cantonese[0] },
			{ name: "Century Egg with Pickled Ginger", price: 38, photoUrl: PHOTO.cantonese[1] },
		],
	},
	{
		name: "Luk Yu Tea House",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Dim Sum",
		rating: 4.1,
		reviewCount: 1580,
		dishes: [
			{ name: "Steamed Shrimp Dumplings", price: 58, photoUrl: PHOTO.dimSum[0] },
			{ name: "Barbecue Pork Bun", price: 46, photoUrl: PHOTO.dimSum[1] },
		],
	},
	{
		name: "The Chairman",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Cantonese",
		rating: 4.7,
		reviewCount: 980,
		dishes: [
			{ name: "Steamed Garoupa with Aged Tangerine Peel", price: 480, photoUrl: PHOTO.cantonese[0] },
			{ name: "Slow-cooked Pork Belly with Preserved Vegetables", price: 220, photoUrl: PHOTO.cantonese[1] },
		],
	},
	{
		name: "Tai Cheong Bakery",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Bakery",
		rating: 4.4,
		reviewCount: 2860,
		dishes: [
			{ name: "Egg Tart", price: 12, photoUrl: PHOTO.bakery[0] },
			{ name: "Coconut Tart", price: 14, photoUrl: PHOTO.bakery[1] },
		],
	},
	{
		name: "Lan Fong Yuen",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Cha Chaan Teng",
		rating: 4.3,
		reviewCount: 4210,
		dishes: [
			{ name: "Silk Stocking Milk Tea", price: 22, photoUrl: PHOTO.chaChaanTeng[0] },
			{ name: "Pork Chop Bun", price: 32, photoUrl: PHOTO.chaChaanTeng[1] },
		],
	},
	{
		name: "Mak's Noodle",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Noodles",
		rating: 4.2,
		reviewCount: 1980,
		dishes: [
			{ name: "Wonton Noodles", price: 46, photoUrl: PHOTO.noodles[0] },
			{ name: "Beef Brisket Noodles", price: 52, photoUrl: PHOTO.noodles[1] },
		],
	},
	{
		name: "Yat Lok",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Cantonese",
		rating: 4.5,
		reviewCount: 2340,
		dishes: [{ name: "Roast Goose Noodles", price: 68, photoUrl: PHOTO.cantonese[0] }],
	},
	{
		name: "Amber",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "French",
		rating: 4.8,
		reviewCount: 720,
		dishes: [
			{ name: "Miyazaki Beef with Black Garlic", price: 680, photoUrl: PHOTO.french[0] },
			{ name: "Hokkaido Sea Urchin with Caviar", price: 420, photoUrl: PHOTO.french[1] },
		],
	},
	{
		name: "Lung King Heen",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Cantonese",
		rating: 4.7,
		reviewCount: 1560,
		dishes: [
			{ name: "Baked Whole Abalone Puff", price: 168, photoUrl: PHOTO.cantonese[0] },
			{ name: "Steamed Lobster with Egg White", price: 380, photoUrl: PHOTO.cantonese[1] },
		],
	},
	{
		name: "8½ Otto e Mezzo Bombana",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Italian",
		rating: 4.8,
		reviewCount: 640,
		dishes: [
			{ name: "Tagliolini with Alba White Truffle", price: 780, photoUrl: PHOTO.italian[0] },
			{ name: "Sea Urchin Spaghetti", price: 420, photoUrl: PHOTO.italian[1] },
		],
	},
	{
		name: "Kau Kee",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Noodles",
		rating: 4.0,
		reviewCount: 3120,
		dishes: [
			{ name: "Beef Brisket Noodles", price: 58, photoUrl: PHOTO.noodles[0] },
			{ name: "Curry Beef Brisket", price: 68, photoUrl: PHOTO.noodles[1] },
		],
	},
	{
		name: "Ho Lee Fook",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Cantonese",
		rating: 4.3,
		reviewCount: 1120,
		dishes: [
			{ name: "Roast Wagyu Short Rib", price: 328, photoUrl: PHOTO.cantonese[0] },
			{ name: "Prawn Toast", price: 138, photoUrl: PHOTO.cantonese[1] },
		],
	},
	{
		name: "Din Tai Fung (Central)",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Taiwanese",
		rating: 4.4,
		reviewCount: 5230,
		dishes: [
			{ name: "Xiao Long Bao", price: 88, photoUrl: PHOTO.taiwanese[0] },
			{ name: "Shrimp Fried Rice", price: 108, photoUrl: PHOTO.taiwanese[1] },
		],
	},
	{
		name: "The Cupping Room",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Cafe",
		rating: 4.3,
		reviewCount: 980,
		dishes: [
			{ name: "Flat White", price: 42, photoUrl: PHOTO.cafe[0] },
			{ name: "Avocado Toast", price: 88, photoUrl: PHOTO.cafe[1] },
		],
	},
	{
		name: "Chilli Fagara",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Sichuan",
		rating: 4.2,
		reviewCount: 870,
		dishes: [
			{ name: "Ma Po Tofu", price: 128, photoUrl: PHOTO.sichuan[0] },
			{ name: "Dan Dan Noodles", price: 78, photoUrl: PHOTO.sichuan[1] },
		],
	},
	{
		name: "Beef & Liberty",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Western",
		rating: 4.2,
		reviewCount: 1340,
		dishes: [{ name: "Bacon Cheeseburger", price: 128, photoUrl: PHOTO.western[1] }],
	},
	{
		name: "Motorino",
		region: "Hong Kong Island",
		district: "Central & Western",
		dishType: "Italian",
		rating: 4.3,
		reviewCount: 760,
		dishes: [{ name: "Margherita Pizza", price: 138, photoUrl: PHOTO.italian[0] }],
	},

	// Wan Chai
	{
		name: "Samsen",
		region: "Hong Kong Island",
		district: "Wan Chai",
		dishType: "Thai",
		rating: 4.6,
		reviewCount: 2140,
		dishes: [
			{ name: "Pad Thai", price: 128, photoUrl: PHOTO.thai[0] },
			{ name: "Boat Noodles", price: 98, photoUrl: PHOTO.thai[1] },
		],
	},
	{
		name: "Under Bridge Spicy Crab",
		region: "Hong Kong Island",
		district: "Wan Chai",
		dishType: "Seafood",
		rating: 4.3,
		reviewCount: 1870,
		dishes: [
			{ name: "Typhoon Shelter Crab", price: 480, photoUrl: PHOTO.seafood[0] },
			{ name: "Garlic Prawns", price: 188, photoUrl: PHOTO.seafood[1] },
		],
	},
	{
		name: "Kam's Roast Goose",
		region: "Hong Kong Island",
		district: "Wan Chai",
		dishType: "Cantonese",
		rating: 4.4,
		reviewCount: 2980,
		dishes: [
			{ name: "Roast Goose", price: 168, photoUrl: PHOTO.cantonese[0] },
			{ name: "Char Siu", price: 88, photoUrl: PHOTO.cantonese[1] },
		],
	},
	{
		name: "Ichiran",
		region: "Hong Kong Island",
		district: "Wan Chai",
		dishType: "Ramen",
		rating: 4.2,
		reviewCount: 3410,
		dishes: [
			{ name: "Tonkotsu Ramen", price: 98, photoUrl: PHOTO.ramen[0] },
			{ name: "Matcha Almond Tofu", price: 38, photoUrl: PHOTO.dessert[0] },
		],
	},
	{
		name: "Ho Hung Kee",
		region: "Hong Kong Island",
		district: "Wan Chai",
		dishType: "Noodles",
		rating: 4.3,
		reviewCount: 2210,
		dishes: [
			{ name: "Wonton Noodles", price: 48, photoUrl: PHOTO.noodles[0] },
			{ name: "Congee with Pork and Century Egg", price: 42, photoUrl: PHOTO.noodles[1] },
		],
	},
	{
		name: "Yee Shun Milk Company",
		region: "Hong Kong Island",
		district: "Wan Chai",
		dishType: "Dessert",
		rating: 4.1,
		reviewCount: 1650,
		dishes: [
			{ name: "Steamed Milk Pudding", price: 32, photoUrl: PHOTO.dessert[1] },
			{ name: "Double Skin Milk", price: 34, photoUrl: PHOTO.dessert[2] },
		],
	},
	{
		name: "Fook Lam Moon",
		region: "Hong Kong Island",
		district: "Wan Chai",
		dishType: "Cantonese",
		rating: 4.6,
		reviewCount: 1240,
		dishes: [
			{ name: "Crispy Chicken", price: 260, photoUrl: PHOTO.cantonese[0] },
			{ name: "Steamed Garoupa", price: 320, photoUrl: PHOTO.cantonese[1] },
		],
	},
	{
		name: "Joy Hing",
		region: "Hong Kong Island",
		district: "Wan Chai",
		dishType: "Cantonese",
		rating: 4.2,
		reviewCount: 3120,
		dishes: [
			{ name: "Char Siu Rice", price: 58, photoUrl: PHOTO.cantonese[0] },
			{ name: "Roast Goose Rice", price: 78, photoUrl: PHOTO.cantonese[1] },
		],
	},
	{
		name: "The Pawn",
		region: "Hong Kong Island",
		district: "Wan Chai",
		dishType: "Western",
		rating: 4.3,
		reviewCount: 760,
		dishes: [
			{ name: "Sunday Roast", price: 288, photoUrl: PHOTO.western[0] },
			{ name: "Fish and Chips", price: 168, photoUrl: PHOTO.western[1] },
		],
	},
	{
		name: "Wu Kong Shanghai Restaurant",
		region: "Hong Kong Island",
		district: "Wan Chai",
		dishType: "Shanghainese",
		rating: 4.1,
		reviewCount: 980,
		dishes: [
			{ name: "Drunken Chicken", price: 98, photoUrl: PHOTO.shanghainese[0] },
			{ name: "Xiao Long Bao", price: 78, photoUrl: PHOTO.shanghainese[1] },
		],
	},
	{
		name: "Sister Wah",
		region: "Hong Kong Island",
		district: "Wan Chai",
		dishType: "Noodles",
		rating: 4.4,
		reviewCount: 1430,
		dishes: [
			{ name: "Beef Brisket Noodles", price: 58, photoUrl: PHOTO.noodles[0] },
			{ name: "Beef Tendon Noodles", price: 62, photoUrl: PHOTO.noodles[1] },
		],
	},
	{
		name: "22 Ships",
		region: "Hong Kong Island",
		district: "Wan Chai",
		dishType: "Western",
		rating: 4.4,
		reviewCount: 690,
		dishes: [
			{ name: "Jamón Ibérico", price: 168, photoUrl: PHOTO.western[0] },
			{ name: "Grilled Octopus", price: 148, photoUrl: PHOTO.western[1] },
		],
	},

	// Eastern
	{
		name: "Tung Po Kitchen",
		region: "Hong Kong Island",
		district: "Eastern",
		dishType: "Cantonese",
		rating: 4.3,
		reviewCount: 1890,
		dishes: [
			{ name: "Crispy Pork Knuckle", price: 188, photoUrl: PHOTO.cantonese[0] },
			{ name: "Typhoon Shelter Prawns", price: 168, photoUrl: PHOTO.seafood[0] },
		],
	},
	{
		name: "Genki Sushi (Tai Koo)",
		region: "Hong Kong Island",
		district: "Eastern",
		dishType: "Sushi",
		rating: 3.9,
		reviewCount: 2450,
		dishes: [
			{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] },
			{ name: "Tamago Sushi", price: 16, photoUrl: PHOTO.sushi[1] },
		],
	},
	{
		name: "Café de Coral (Quarry Bay)",
		region: "Hong Kong Island",
		district: "Eastern",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 5230,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Fairwood (Quarry Bay)",
		region: "Hong Kong Island",
		district: "Eastern",
		dishType: "Cha Chaan Teng",
		rating: 3.6,
		reviewCount: 4120,
		dishes: [{ name: "Sliced Beef Rice", price: 48, photoUrl: PHOTO.chaChaanTeng[1] }],
	},
	{
		name: "PizzaExpress (Quarry Bay)",
		region: "Hong Kong Island",
		district: "Eastern",
		dishType: "Italian",
		rating: 4.0,
		reviewCount: 870,
		dishes: [
			{ name: "Margherita", price: 118, photoUrl: PHOTO.italian[0] },
			{ name: "Sloppy Giuseppe", price: 148, photoUrl: PHOTO.italian[1] },
		],
	},
	{
		name: "Ootoya (Tai Koo)",
		region: "Hong Kong Island",
		district: "Eastern",
		dishType: "Japanese",
		rating: 4.1,
		reviewCount: 980,
		dishes: [
			{ name: "Chicken Nanban", price: 108, photoUrl: PHOTO.japanese[0] },
			{ name: "Grilled Saba", price: 118, photoUrl: PHOTO.japanese[1] },
		],
	},
	{
		name: "Mou Mou Club (Tai Koo)",
		region: "Hong Kong Island",
		district: "Eastern",
		dishType: "Hot Pot",
		rating: 4.2,
		reviewCount: 760,
		dishes: [
			{ name: "Beef Platter", price: 228, photoUrl: PHOTO.hotPot[0] },
			{ name: "Tomato Broth", price: 68, photoUrl: PHOTO.hotPot[1] },
		],
	},
	{
		name: "Tai Hing (North Point)",
		region: "Hong Kong Island",
		district: "Eastern",
		dishType: "Cha Chaan Teng",
		rating: 3.8,
		reviewCount: 1870,
		dishes: [{ name: "Roast Pork Rice", price: 58, photoUrl: PHOTO.chaChaanTeng[0] }],
	},

	// Southern
	{
		name: "The Verandah",
		region: "Hong Kong Island",
		district: "Southern",
		dishType: "French",
		rating: 4.6,
		reviewCount: 540,
		dishes: [
			{ name: "Seafood Platter", price: 588, photoUrl: PHOTO.french[0] },
			{ name: "Lobster Bisque", price: 168, photoUrl: PHOTO.french[1] },
		],
	},
	{
		name: "The Boathouse",
		region: "Hong Kong Island",
		district: "Southern",
		dishType: "Seafood",
		rating: 4.1,
		reviewCount: 880,
		dishes: [
			{ name: "Fish and Chips", price: 168, photoUrl: PHOTO.seafood[0] },
			{ name: "Mussels in White Wine", price: 158, photoUrl: PHOTO.seafood[1] },
		],
	},
	{
		name: "Lucy's",
		region: "Hong Kong Island",
		district: "Southern",
		dishType: "Western",
		rating: 4.3,
		reviewCount: 620,
		dishes: [
			{ name: "Ribeye Steak", price: 298, photoUrl: PHOTO.western[0] },
			{ name: "Truffle Fries", price: 78, photoUrl: PHOTO.western[1] },
		],
	},
	{
		name: "Café de Coral (Ap Lei Chau)",
		region: "Hong Kong Island",
		district: "Southern",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 3120,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Genki Sushi (Ap Lei Chau)",
		region: "Hong Kong Island",
		district: "Southern",
		dishType: "Sushi",
		rating: 3.8,
		reviewCount: 1430,
		dishes: [{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] }],
	},
	{
		name: "PizzaExpress (Stanley)",
		region: "Hong Kong Island",
		district: "Southern",
		dishType: "Italian",
		rating: 3.9,
		reviewCount: 760,
		dishes: [{ name: "Margherita", price: 118, photoUrl: PHOTO.italian[0] }],
	},

	// ---------------------------------------------------------------------------
	// Kowloon
	// ---------------------------------------------------------------------------
	// Yau Tsim Mong
	{
		name: "Spring Deer",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Shanghainese",
		rating: 4.3,
		reviewCount: 1420,
		dishes: [
			{ name: "Peking Duck", price: 288, photoUrl: PHOTO.shanghainese[0] },
			{ name: "Xiao Long Bao", price: 78, photoUrl: PHOTO.shanghainese[1] },
		],
	},
	{
		name: "Australia Dairy Company",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Cha Chaan Teng",
		rating: 4.2,
		reviewCount: 5230,
		dishes: [
			{ name: "Scrambled Egg Toast", price: 42, photoUrl: PHOTO.chaChaanTeng[0] },
			{ name: "Steamed Egg Pudding", price: 32, photoUrl: PHOTO.dessert[0] },
		],
	},
	{
		name: "Mak Man Kee",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Noodles",
		rating: 4.3,
		reviewCount: 1890,
		dishes: [
			{ name: "Wonton Noodles", price: 48, photoUrl: PHOTO.noodles[0] },
			{ name: "Beef Brisket Noodles", price: 58, photoUrl: PHOTO.noodles[1] },
		],
	},
	{
		name: "Mido Café",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Cha Chaan Teng",
		rating: 4.0,
		reviewCount: 1980,
		dishes: [
			{ name: "French Toast", price: 42, photoUrl: PHOTO.chaChaanTeng[1] },
			{ name: "Baked Pork Chop Rice", price: 58, photoUrl: PHOTO.chaChaanTeng[0] },
		],
	},
	{
		name: "Hing Kee Claypot Rice",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Cantonese",
		rating: 4.1,
		reviewCount: 1340,
		dishes: [
			{ name: "Claypot Rice with Preserved Sausage", price: 68, photoUrl: PHOTO.cantonese[0] },
			{ name: "Black Pepper Beef Claypot Rice", price: 78, photoUrl: PHOTO.cantonese[1] },
		],
	},
	{
		name: "Kung Wo Tong",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Dessert",
		rating: 4.2,
		reviewCount: 1120,
		dishes: [
			{ name: "Sesame Paste", price: 32, photoUrl: PHOTO.dessert[1] },
			{ name: "Walnut Soup", price: 34, photoUrl: PHOTO.dessert[2] },
		],
	},
	{
		name: "Cheung Hing Kee",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Street Food",
		rating: 4.4,
		reviewCount: 2340,
		dishes: [
			{ name: "Pan-fried Pork Buns", price: 36, photoUrl: PHOTO.street[0] },
			{ name: "Xiao Long Bao", price: 42, photoUrl: PHOTO.street[1] },
		],
	},
	{
		name: "Kam Wah Café",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Cha Chaan Teng",
		rating: 4.3,
		reviewCount: 3120,
		dishes: [
			{ name: "Pineapple Bun with Butter", price: 28, photoUrl: PHOTO.bakery[0] },
			{ name: "Silk Stocking Milk Tea", price: 22, photoUrl: PHOTO.chaChaanTeng[0] },
		],
	},
	{
		name: "T'ang Court",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Cantonese",
		rating: 4.7,
		reviewCount: 860,
		dishes: [
			{ name: "Steamed Garoupa", price: 380, photoUrl: PHOTO.cantonese[0] },
			{ name: "Barbecue Pork with Honey", price: 128, photoUrl: PHOTO.cantonese[1] },
		],
	},
	{
		name: "Ming Court",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Cantonese",
		rating: 4.6,
		reviewCount: 940,
		dishes: [
			{ name: "Roast Goose", price: 188, photoUrl: PHOTO.cantonese[0] },
			{ name: "Dim Sum Platter", price: 168, photoUrl: PHOTO.dimSum[0] },
		],
	},
	{
		name: "Din Tai Fung (TST)",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Taiwanese",
		rating: 4.4,
		reviewCount: 4120,
		dishes: [
			{ name: "Xiao Long Bao", price: 88, photoUrl: PHOTO.taiwanese[0] },
			{ name: "Shrimp and Pork Dumplings", price: 78, photoUrl: PHOTO.taiwanese[1] },
		],
	},
	{
		name: "Tasty Congee & Noodle Wantun Shop",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Noodles",
		rating: 4.1,
		reviewCount: 1230,
		dishes: [
			{ name: "Congee with Century Egg", price: 42, photoUrl: PHOTO.noodles[1] },
			{ name: "Wonton Noodles", price: 52, photoUrl: PHOTO.noodles[0] },
		],
	},
	{
		name: "Yat Tung Heen",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Cantonese",
		rating: 4.5,
		reviewCount: 780,
		dishes: [
			{ name: "Steamed Garoupa", price: 320, photoUrl: PHOTO.cantonese[0] },
			{ name: "Wagyu Beef Puff", price: 88, photoUrl: PHOTO.dimSum[1] },
		],
	},
	{
		name: "Tsui Wah (TST)",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Cha Chaan Teng",
		rating: 3.9,
		reviewCount: 6120,
		dishes: [
			{ name: "Fish Maw Soup", price: 62, photoUrl: PHOTO.chaChaanTeng[0] },
			{ name: "Crispy Bun with Condensed Milk", price: 28, photoUrl: PHOTO.bakery[1] },
		],
	},
	{
		name: "Mammy Pancake",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Street Food",
		rating: 4.4,
		reviewCount: 2560,
		dishes: [{ name: "Egg Waffle", price: 28, photoUrl: PHOTO.street[2] }],
	},
	{
		name: "Yoshinoya (Mong Kok)",
		region: "Kowloon",
		district: "Yau Tsim Mong",
		dishType: "Japanese",
		rating: 3.7,
		reviewCount: 3120,
		dishes: [{ name: "Beef Bowl", price: 48, photoUrl: PHOTO.japanese[2] }],
	},

	// Sham Shui Po
	{
		name: "Tim Ho Wan",
		region: "Kowloon",
		district: "Sham Shui Po",
		dishType: "Dim Sum",
		rating: 4.3,
		reviewCount: 5230,
		dishes: [
			{ name: "Baked BBQ Pork Bun", price: 32, photoUrl: PHOTO.dimSum[0] },
			{ name: "Har Gow", price: 40, photoUrl: PHOTO.dimSum[1] },
		],
	},
	{
		name: "Kung Wo Beancurd Factory",
		region: "Kowloon",
		district: "Sham Shui Po",
		dishType: "Dessert",
		rating: 4.2,
		reviewCount: 2340,
		dishes: [
			{ name: "Tofu Pudding", price: 18, photoUrl: PHOTO.dessert[3] },
			{ name: "Fried Tofu", price: 22, photoUrl: PHOTO.street[0] },
		],
	},
	{
		name: "Hop Yik Tai",
		region: "Kowloon",
		district: "Sham Shui Po",
		dishType: "Street Food",
		rating: 4.4,
		reviewCount: 2890,
		dishes: [
			{ name: "Cheung Fun with Sweet Sauce", price: 18, photoUrl: PHOTO.street[0] },
			{ name: "Curry Fish Balls", price: 16, photoUrl: PHOTO.street[2] },
		],
	},
	{
		name: "Lau Sum Kee",
		region: "Kowloon",
		district: "Sham Shui Po",
		dishType: "Noodles",
		rating: 4.3,
		reviewCount: 1560,
		dishes: [
			{ name: "Bamboo Pressed Noodles", price: 52, photoUrl: PHOTO.noodles[0] },
			{ name: "Wonton Noodles", price: 48, photoUrl: PHOTO.noodles[1] },
		],
	},
	{
		name: "Shin Kee Beef Brisket",
		region: "Kowloon",
		district: "Sham Shui Po",
		dishType: "Noodles",
		rating: 4.1,
		reviewCount: 1230,
		dishes: [
			{ name: "Beef Brisket Noodles", price: 56, photoUrl: PHOTO.noodles[0] },
			{ name: "Beef Tendon Noodles", price: 60, photoUrl: PHOTO.noodles[1] },
		],
	},
	{
		name: "Kwan Kee Claypot Rice",
		region: "Kowloon",
		district: "Sham Shui Po",
		dishType: "Cantonese",
		rating: 4.0,
		reviewCount: 870,
		dishes: [
			{ name: "Claypot Rice with Preserved Sausage", price: 68, photoUrl: PHOTO.cantonese[0] },
			{ name: "Frog Claypot Rice", price: 88, photoUrl: PHOTO.cantonese[1] },
		],
	},
	{
		name: "Café de Coral (Sham Shui Po)",
		region: "Kowloon",
		district: "Sham Shui Po",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 4120,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Genki Sushi (Sham Shui Po)",
		region: "Kowloon",
		district: "Sham Shui Po",
		dishType: "Sushi",
		rating: 3.8,
		reviewCount: 2140,
		dishes: [{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] }],
	},

	// Kowloon City
	{
		name: "Islam Food",
		region: "Kowloon",
		district: "Kowloon City",
		dishType: "Indian",
		rating: 4.2,
		reviewCount: 1980,
		dishes: [
			{ name: "Pan-fried Beef Balls", price: 68, photoUrl: PHOTO.indian[0] },
			{ name: "Lamb Curry", price: 98, photoUrl: PHOTO.indian[1] },
		],
	},
	{
		name: "Bangkok Restaurant",
		region: "Kowloon",
		district: "Kowloon City",
		dishType: "Thai",
		rating: 4.1,
		reviewCount: 1230,
		dishes: [
			{ name: "Tom Yum Goong", price: 88, photoUrl: PHOTO.thai[0] },
			{ name: "Green Curry", price: 78, photoUrl: PHOTO.thai[1] },
		],
	},
	{
		name: "Koon Thai",
		region: "Kowloon",
		district: "Kowloon City",
		dishType: "Thai",
		rating: 4.0,
		reviewCount: 980,
		dishes: [
			{ name: "Pad Thai", price: 78, photoUrl: PHOTO.thai[0] },
			{ name: "Thai Basil Chicken", price: 68, photoUrl: PHOTO.thai[1] },
		],
	},
	{
		name: "Fung Shing Restaurant",
		region: "Kowloon",
		district: "Kowloon City",
		dishType: "Cantonese",
		rating: 4.1,
		reviewCount: 1340,
		dishes: [
			{ name: "Roast Pigeon", price: 98, photoUrl: PHOTO.cantonese[0] },
			{ name: "Salt-baked Chicken", price: 168, photoUrl: PHOTO.cantonese[1] },
		],
	},
	{
		name: "Fairwood (Kowloon City)",
		region: "Kowloon",
		district: "Kowloon City",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 2760,
		dishes: [{ name: "Sliced Beef Rice", price: 48, photoUrl: PHOTO.chaChaanTeng[1] }],
	},
	{
		name: "Ajisen Ramen (Kowloon City)",
		region: "Kowloon",
		district: "Kowloon City",
		dishType: "Ramen",
		rating: 3.8,
		reviewCount: 1980,
		dishes: [{ name: "Tonkotsu Ramen", price: 72, photoUrl: PHOTO.ramen[0] }],
	},

	// Wong Tai Sin
	{
		name: "Shanghai Lao Lao",
		region: "Kowloon",
		district: "Wong Tai Sin",
		dishType: "Shanghainese",
		rating: 4.2,
		reviewCount: 1780,
		dishes: [
			{ name: "Steamed Pork Dumplings", price: 68, photoUrl: PHOTO.shanghainese[0] },
			{ name: "Drunken Chicken", price: 88, photoUrl: PHOTO.shanghainese[1] },
		],
	},
	{
		name: "Genki Sushi (Wong Tai Sin)",
		region: "Kowloon",
		district: "Wong Tai Sin",
		dishType: "Sushi",
		rating: 3.8,
		reviewCount: 1650,
		dishes: [{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] }],
	},
	{
		name: "Fairwood (San Po Kong)",
		region: "Kowloon",
		district: "Wong Tai Sin",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 2340,
		dishes: [{ name: "Chicken Curry Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Tai Hing (Diamond Hill)",
		region: "Kowloon",
		district: "Wong Tai Sin",
		dishType: "Cha Chaan Teng",
		rating: 3.8,
		reviewCount: 1980,
		dishes: [{ name: "Roast Pork Rice", price: 58, photoUrl: PHOTO.chaChaanTeng[1] }],
	},
	{
		name: "Ajisen Ramen (Wong Tai Sin)",
		region: "Kowloon",
		district: "Wong Tai Sin",
		dishType: "Ramen",
		rating: 3.8,
		reviewCount: 1560,
		dishes: [{ name: "Spicy Ramen", price: 76, photoUrl: PHOTO.ramen[1] }],
	},
	{
		name: "Café de Coral (Tsz Wan Shan)",
		region: "Kowloon",
		district: "Wong Tai Sin",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 2890,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},

	// Kwun Tong
	{
		name: "Café de Coral (Kwun Tong)",
		region: "Kowloon",
		district: "Kwun Tong",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 3450,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Genki Sushi (Kwun Tong)",
		region: "Kowloon",
		district: "Kwun Tong",
		dishType: "Sushi",
		rating: 3.8,
		reviewCount: 2210,
		dishes: [{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] }],
	},
	{
		name: "Ajisen Ramen (Kwun Tong)",
		region: "Kowloon",
		district: "Kwun Tong",
		dishType: "Ramen",
		rating: 3.8,
		reviewCount: 1870,
		dishes: [{ name: "Tonkotsu Ramen", price: 72, photoUrl: PHOTO.ramen[0] }],
	},
	{
		name: "Yoshinoya (Ngau Tau Kok)",
		region: "Kowloon",
		district: "Kwun Tong",
		dishType: "Japanese",
		rating: 3.7,
		reviewCount: 2650,
		dishes: [{ name: "Beef Bowl", price: 48, photoUrl: PHOTO.japanese[2] }],
	},
	{
		name: "Fairwood (Lam Tin)",
		region: "Kowloon",
		district: "Kwun Tong",
		dishType: "Cha Chaan Teng",
		rating: 3.6,
		reviewCount: 3120,
		dishes: [{ name: "Sliced Beef Rice", price: 48, photoUrl: PHOTO.chaChaanTeng[1] }],
	},
	{
		name: "Tai Hing (Kwun Tong)",
		region: "Kowloon",
		district: "Kwun Tong",
		dishType: "Cha Chaan Teng",
		rating: 3.8,
		reviewCount: 2430,
		dishes: [{ name: "Roast Pork Rice", price: 58, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Pizza Hut (Kwun Tong)",
		region: "Kowloon",
		district: "Kwun Tong",
		dishType: "Italian",
		rating: 3.6,
		reviewCount: 1980,
		dishes: [{ name: "Supreme Pizza", price: 138, photoUrl: PHOTO.italian[0] }],
	},

	// ---------------------------------------------------------------------------
	// New Territories East
	// ---------------------------------------------------------------------------
	// North
	{
		name: "Café de Coral (Fanling)",
		region: "New Territories East",
		district: "North",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 2650,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Fairwood (Sheung Shui)",
		region: "New Territories East",
		district: "North",
		dishType: "Cha Chaan Teng",
		rating: 3.6,
		reviewCount: 2210,
		dishes: [{ name: "Sliced Beef Rice", price: 48, photoUrl: PHOTO.chaChaanTeng[1] }],
	},
	{
		name: "Genki Sushi (Sheung Shui)",
		region: "New Territories East",
		district: "North",
		dishType: "Sushi",
		rating: 3.8,
		reviewCount: 1780,
		dishes: [{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] }],
	},
	{
		name: "Ajisen Ramen (Fanling)",
		region: "New Territories East",
		district: "North",
		dishType: "Ramen",
		rating: 3.8,
		reviewCount: 1540,
		dishes: [{ name: "Tonkotsu Ramen", price: 72, photoUrl: PHOTO.ramen[0] }],
	},
	{
		name: "Yoshinoya (Sheung Shui)",
		region: "New Territories East",
		district: "North",
		dishType: "Japanese",
		rating: 3.7,
		reviewCount: 1980,
		dishes: [{ name: "Beef Bowl", price: 48, photoUrl: PHOTO.japanese[2] }],
	},

	// Tai Po
	{
		name: "Chan Kun Kee",
		region: "New Territories East",
		district: "Tai Po",
		dishType: "Cantonese",
		rating: 4.1,
		reviewCount: 2340,
		dishes: [
			{ name: "Salt-baked Chicken", price: 168, photoUrl: PHOTO.cantonese[0] },
			{ name: "Claypot Rice", price: 68, photoUrl: PHOTO.cantonese[1] },
		],
	},
	{
		name: "Café de Coral (Tai Po)",
		region: "New Territories East",
		district: "Tai Po",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 2980,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Fairwood (Tai Po)",
		region: "New Territories East",
		district: "Tai Po",
		dishType: "Cha Chaan Teng",
		rating: 3.6,
		reviewCount: 2140,
		dishes: [{ name: "Chicken Curry Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[1] }],
	},
	{
		name: "Tai Hing (Tai Po)",
		region: "New Territories East",
		district: "Tai Po",
		dishType: "Cha Chaan Teng",
		rating: 3.8,
		reviewCount: 1870,
		dishes: [{ name: "Roast Pork Rice", price: 58, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Genki Sushi (Tai Po)",
		region: "New Territories East",
		district: "Tai Po",
		dishType: "Sushi",
		rating: 3.8,
		reviewCount: 1650,
		dishes: [{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] }],
	},

	// Sha Tin
	{
		name: "Sha Tin 18",
		region: "New Territories East",
		district: "Sha Tin",
		dishType: "Cantonese",
		rating: 4.5,
		reviewCount: 980,
		dishes: [
			{ name: "Peking Duck", price: 398, photoUrl: PHOTO.cantonese[0] },
			{ name: "Steamed Garoupa", price: 320, photoUrl: PHOTO.cantonese[1] },
		],
	},
	{
		name: "Café de Coral (Sha Tin)",
		region: "New Territories East",
		district: "Sha Tin",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 3210,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Fairwood (Sha Tin)",
		region: "New Territories East",
		district: "Sha Tin",
		dishType: "Cha Chaan Teng",
		rating: 3.6,
		reviewCount: 2450,
		dishes: [{ name: "Sliced Beef Rice", price: 48, photoUrl: PHOTO.chaChaanTeng[1] }],
	},
	{
		name: "Genki Sushi (Sha Tin)",
		region: "New Territories East",
		district: "Sha Tin",
		dishType: "Sushi",
		rating: 3.8,
		reviewCount: 1980,
		dishes: [{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] }],
	},
	{
		name: "Yoshinoya (Sha Tin)",
		region: "New Territories East",
		district: "Sha Tin",
		dishType: "Japanese",
		rating: 3.7,
		reviewCount: 2210,
		dishes: [{ name: "Beef Bowl", price: 48, photoUrl: PHOTO.japanese[2] }],
	},
	{
		name: "Pizza Hut (Sha Tin)",
		region: "New Territories East",
		district: "Sha Tin",
		dishType: "Italian",
		rating: 3.6,
		reviewCount: 1760,
		dishes: [{ name: "Supreme Pizza", price: 138, photoUrl: PHOTO.italian[0] }],
	},

	// Sai Kung
	{
		name: "Loaf On",
		region: "New Territories East",
		district: "Sai Kung",
		dishType: "Seafood",
		rating: 4.5,
		reviewCount: 1240,
		dishes: [
			{ name: "Steamed Garoupa", price: 380, photoUrl: PHOTO.seafood[0] },
			{ name: "Salt and Pepper Squid", price: 168, photoUrl: PHOTO.seafood[1] },
		],
	},
	{
		name: "Chuen Kee Seafood Restaurant",
		region: "New Territories East",
		district: "Sai Kung",
		dishType: "Seafood",
		rating: 4.2,
		reviewCount: 2130,
		dishes: [
			{ name: "Steamed Prawns", price: 288, photoUrl: PHOTO.seafood[1] },
			{ name: "Garlic Steamed Scallops", price: 198, photoUrl: PHOTO.seafood[2] },
		],
	},
	{
		name: "Tung Kee Seafood",
		region: "New Territories East",
		district: "Sai Kung",
		dishType: "Seafood",
		rating: 4.1,
		reviewCount: 1560,
		dishes: [{ name: "Typhoon Shelter Crab", price: 468, photoUrl: PHOTO.seafood[0] }],
	},
	{
		name: "Sai Kung Cafe & Bakery",
		region: "New Territories East",
		district: "Sai Kung",
		dishType: "Bakery",
		rating: 4.3,
		reviewCount: 3120,
		dishes: [
			{ name: "Portuguese Egg Tart", price: 16, photoUrl: PHOTO.bakery[0] },
			{ name: "Pineapple Bun", price: 18, photoUrl: PHOTO.bakery[1] },
		],
	},
	{
		name: "Café de Coral (Sai Kung)",
		region: "New Territories East",
		district: "Sai Kung",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 1870,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Genki Sushi (Sai Kung)",
		region: "New Territories East",
		district: "Sai Kung",
		dishType: "Sushi",
		rating: 3.8,
		reviewCount: 1340,
		dishes: [{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] }],
	},

	// ---------------------------------------------------------------------------
	// New Territories West
	// ---------------------------------------------------------------------------
	// Islands
	{
		name: "Kam Wing Tai",
		region: "New Territories West",
		district: "Islands",
		dishType: "Seafood",
		rating: 4.2,
		reviewCount: 1780,
		dishes: [
			{ name: "Steamed Prawns", price: 268, photoUrl: PHOTO.seafood[1] },
			{ name: "Salt and Pepper Squid", price: 158, photoUrl: PHOTO.seafood[0] },
		],
	},
	{
		name: "Wah Kee Big Fish Ball",
		region: "New Territories West",
		district: "Islands",
		dishType: "Street Food",
		rating: 4.3,
		reviewCount: 2560,
		dishes: [{ name: "Big Fish Ball Skewer", price: 20, photoUrl: PHOTO.street[2] }],
	},
	{
		name: "Kwok Kam Kee Bakery",
		region: "New Territories West",
		district: "Islands",
		dishType: "Bakery",
		rating: 4.1,
		reviewCount: 1430,
		dishes: [{ name: "Mango Mochi", price: 22, photoUrl: PHOTO.bakery[0] }],
	},
	{
		name: "Sok Kwu Wan Seafood (Lamma)",
		region: "New Territories West",
		district: "Islands",
		dishType: "Seafood",
		rating: 4.2,
		reviewCount: 1230,
		dishes: [{ name: "Steamed Garoupa", price: 358, photoUrl: PHOTO.seafood[2] }],
	},
	{
		name: "Café de Coral (Tung Chung)",
		region: "New Territories West",
		district: "Islands",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 2340,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Genki Sushi (Tung Chung)",
		region: "New Territories West",
		district: "Islands",
		dishType: "Sushi",
		rating: 3.8,
		reviewCount: 1650,
		dishes: [{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] }],
	},

	// Kwai Tsing
	{
		name: "Café de Coral (Kwai Fong)",
		region: "New Territories West",
		district: "Kwai Tsing",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 3120,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Fairwood (Tsing Yi)",
		region: "New Territories West",
		district: "Kwai Tsing",
		dishType: "Cha Chaan Teng",
		rating: 3.6,
		reviewCount: 2210,
		dishes: [{ name: "Sliced Beef Rice", price: 48, photoUrl: PHOTO.chaChaanTeng[1] }],
	},
	{
		name: "Genki Sushi (Tsing Yi)",
		region: "New Territories West",
		district: "Kwai Tsing",
		dishType: "Sushi",
		rating: 3.8,
		reviewCount: 1780,
		dishes: [{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] }],
	},
	{
		name: "Yoshinoya (Kwai Chung)",
		region: "New Territories West",
		district: "Kwai Tsing",
		dishType: "Japanese",
		rating: 3.7,
		reviewCount: 1980,
		dishes: [{ name: "Beef Bowl", price: 48, photoUrl: PHOTO.japanese[2] }],
	},
	{
		name: "Tai Hing (Kwai Fong)",
		region: "New Territories West",
		district: "Kwai Tsing",
		dishType: "Cha Chaan Teng",
		rating: 3.8,
		reviewCount: 2430,
		dishes: [{ name: "Roast Pork Rice", price: 58, photoUrl: PHOTO.chaChaanTeng[0] }],
	},

	// Tsuen Wan
	{
		name: "Café de Coral (Tsuen Wan)",
		region: "New Territories West",
		district: "Tsuen Wan",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 2980,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Fairwood (Tsuen Wan)",
		region: "New Territories West",
		district: "Tsuen Wan",
		dishType: "Cha Chaan Teng",
		rating: 3.6,
		reviewCount: 2140,
		dishes: [{ name: "Chicken Curry Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[1] }],
	},
	{
		name: "Genki Sushi (Tsuen Wan)",
		region: "New Territories West",
		district: "Tsuen Wan",
		dishType: "Sushi",
		rating: 3.8,
		reviewCount: 1870,
		dishes: [{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] }],
	},
	{
		name: "Ajisen Ramen (Tsuen Wan)",
		region: "New Territories West",
		district: "Tsuen Wan",
		dishType: "Ramen",
		rating: 3.8,
		reviewCount: 1650,
		dishes: [{ name: "Tonkotsu Ramen", price: 72, photoUrl: PHOTO.ramen[0] }],
	},
	{
		name: "Tai Hing (Tsuen Wan)",
		region: "New Territories West",
		district: "Tsuen Wan",
		dishType: "Cha Chaan Teng",
		rating: 3.8,
		reviewCount: 2080,
		dishes: [{ name: "Roast Pork Rice", price: 58, photoUrl: PHOTO.chaChaanTeng[0] }],
	},

	// Tuen Mun
	{
		name: "Café de Coral (Tuen Mun)",
		region: "New Territories West",
		district: "Tuen Mun",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 2760,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Fairwood (Tuen Mun)",
		region: "New Territories West",
		district: "Tuen Mun",
		dishType: "Cha Chaan Teng",
		rating: 3.6,
		reviewCount: 1980,
		dishes: [{ name: "Sliced Beef Rice", price: 48, photoUrl: PHOTO.chaChaanTeng[1] }],
	},
	{
		name: "Genki Sushi (Tuen Mun)",
		region: "New Territories West",
		district: "Tuen Mun",
		dishType: "Sushi",
		rating: 3.8,
		reviewCount: 1760,
		dishes: [{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] }],
	},
	{
		name: "Ajisen Ramen (Tuen Mun)",
		region: "New Territories West",
		district: "Tuen Mun",
		dishType: "Ramen",
		rating: 3.8,
		reviewCount: 1540,
		dishes: [{ name: "Spicy Ramen", price: 76, photoUrl: PHOTO.ramen[1] }],
	},
	{
		name: "Yoshinoya (Tuen Mun)",
		region: "New Territories West",
		district: "Tuen Mun",
		dishType: "Japanese",
		rating: 3.7,
		reviewCount: 1870,
		dishes: [{ name: "Beef Bowl", price: 48, photoUrl: PHOTO.japanese[2] }],
	},

	// Yuen Long
	{
		name: "Kai Kee Dessert",
		region: "New Territories West",
		district: "Yuen Long",
		dishType: "Dessert",
		rating: 4.3,
		reviewCount: 3120,
		dishes: [
			{ name: "B Chai Grass Jelly", price: 68, photoUrl: PHOTO.dessert[0] },
			{ name: "Mango Sago", price: 42, photoUrl: PHOTO.dessert[3] },
		],
	},
	{
		name: "Ho To Tai Noodle Shop",
		region: "New Territories West",
		district: "Yuen Long",
		dishType: "Noodles",
		rating: 4.2,
		reviewCount: 2340,
		dishes: [
			{ name: "Wonton Noodles", price: 46, photoUrl: PHOTO.noodles[0] },
			{ name: "Beef Brisket Noodles", price: 56, photoUrl: PHOTO.noodles[1] },
		],
	},
	{
		name: "Café de Coral (Yuen Long)",
		region: "New Territories West",
		district: "Yuen Long",
		dishType: "Cha Chaan Teng",
		rating: 3.7,
		reviewCount: 2650,
		dishes: [{ name: "Baked Pork Chop Rice", price: 52, photoUrl: PHOTO.chaChaanTeng[0] }],
	},
	{
		name: "Fairwood (Yuen Long)",
		region: "New Territories West",
		district: "Yuen Long",
		dishType: "Cha Chaan Teng",
		rating: 3.6,
		reviewCount: 1980,
		dishes: [{ name: "Sliced Beef Rice", price: 48, photoUrl: PHOTO.chaChaanTeng[1] }],
	},
	{
		name: "Genki Sushi (Yuen Long)",
		region: "New Territories West",
		district: "Yuen Long",
		dishType: "Sushi",
		rating: 3.8,
		reviewCount: 1650,
		dishes: [{ name: "Salmon Sushi", price: 22, photoUrl: PHOTO.sushi[0] }],
	},
	{
		name: "Ajisen Ramen (Yuen Long)",
		region: "New Territories West",
		district: "Yuen Long",
		dishType: "Ramen",
		rating: 3.8,
		reviewCount: 1430,
		dishes: [{ name: "Tonkotsu Ramen", price: 72, photoUrl: PHOTO.ramen[0] }],
	},
];
